# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d5b5b42e1298c93ad5c48321704586a96c3fbdd4f3c58e0ae7ab380841388d5f6558a53d00a7929eb0829bbd66f679b3a59a44bbdd1a10ec5a90b8b570694e

test:
  secret_key_base: c094c27fa571734cd921d541d92e583018dec363a695749fd0d486ea8b6b20f8fe948ef0451750251b7210d8b8e464f86db44412bf01fe7721648842b6a5837b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
